export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART'
export const DELETE_CART = 'DELETE_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'

export const GET_ALL_CART_REQUEST = 'GET_ALL_CART_REQUEST'
export const GET_ALL_CART_SUCCESS = 'GET_ALL_CART_SUCCESS'
export const GET_ALL_CART_FAIL = 'GET_ALL_CART_FAIL'

export const CREATE_CART_REQUEST = 'CREATE_CART_REQUEST'
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS'
export const CREATE_CART_FAIL = 'CREATE_CART_FAIL'
